// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package am.ik.rsocket.protobuf;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:am.ik.rsocket.protobuf.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   * @return The reply.
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   * @return The bytes for reply.
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
