// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package am.ik.rsocket.protobuf;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_am_ik_rsocket_protobuf_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_am_ik_rsocket_protobuf_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_am_ik_rsocket_protobuf_HelloResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_am_ik_rsocket_protobuf_HelloResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\026am.ik.rsocket.protobuf\" \n" +
      "\014HelloRequest\022\020\n\010greeting\030\001 \001(\t\"\036\n\rHello" +
      "Response\022\r\n\005reply\030\001 \001(\tB&\n\026am.ik.rsocket" +
      ".protobufB\nHelloProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_am_ik_rsocket_protobuf_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_am_ik_rsocket_protobuf_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_am_ik_rsocket_protobuf_HelloRequest_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_am_ik_rsocket_protobuf_HelloResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_am_ik_rsocket_protobuf_HelloResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_am_ik_rsocket_protobuf_HelloResponse_descriptor,
        new java.lang.String[] { "Reply", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
