name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        gu-binary: [gu, gu.cmd]
        exclude:
        - os: ubuntu-latest
          gu-binary: gu.cmd
        - os: macos-latest
          gu-binary: gu.cmd
        - os: windows-latest
          gu-binary: gu
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '21.0.0.java8'
    - name: install native-image
      run: |
        ${{ matrix.gu-binary }} install native-image
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      run: |
        set -ex
        mvn -V test
    - name: mvn package
      run: |
        mvn -V package -Pnative -Dmaven.test.skip=true
        mkdir dist
        cp target/classes/rsc-e2e* ./dist/rsc-e2e-${{ runner.os }}
        chmod +x ./dist/rsc-e2e-${{ runner.os }}
    - name: upload-dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
    - name: mvn spring-boot:build-image
      if: github.ref == 'refs/heads/main' && runner.os == 'Linux'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        mvn -V spring-boot:build-image -Dspring-boot.build-image.imageName=${DOCKER_REGISTRY} -Dspring-boot.build-image.publish=true -Dmaven.test.skip=true
