name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          file: rsc-x86_64-pc-linux
          args: --best --lzma
          strip: true
        - os: windows-latest
          file: rsc-x86_64-pc-win32.exe
          args: -9
          strip: false
        - os: macos-latest
          file: rsc-x86_64-apple-darwin
          args: --best
          strip: true
    steps:
    - uses: actions/checkout@v2
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 8
        graalvm-version: 20.3.1
        native-image: true
    - uses: ilammy/msvc-dev-cmd@v1.5.0
      if: runner.os == 'Windows'
    - uses: microsoft/setup-msbuild@v1
      if: runner.os == 'Windows'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn package
      run: |
        mkdir dist
        mvn -DskipTests -Dnative-build-dir=dist -Dnative-build-name=${{ matrix.file }} -V package -P native
    - uses: svenstaro/upx-action@v2
      with:
        file: dist/${{ matrix.file }}
        args: ${{ matrix.args }}
        strip: ${{ matrix.strip }}
