name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        #- ubuntu-latest
        #- macos-latest
        - windows-latest
        gu-binary: [gu, gu.cmd]
        exclude:
        #- os: ubuntu-latest
        #  gu-binary: gu.cmd
        #- os: macos-latest
        #  gu-binary: gu.cmd
        - os: windows-latest
          gu-binary: gu
    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: '20.3.0.java11'
    - name: install native-image
      run: |
        ${{ matrix.gu-binary }} install native-image
    - uses: ilammy/msvc-dev-cmd@v1.5.0
    - uses: microsoft/setup-msbuild@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn package
      run: |
        mvn -DskipTests -V package -P native
