name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          file: rsc-e2e-x86_64-pc-linux
          classifier: linux-x86_64
          move: mv
          separator: /
          extension: ""
        - os: windows-latest
          file: rsc-e2e-x86_64-pc-win32.exe
          classifier: windows-x86_64
          move: move
          separator: \
          extension: .exe
        - os: macos-latest
          file: rsc-e2e-x86_64-apple-darwin
          classifier: osx-x86_64
          move: mv
          separator: /
          extension: ""
    steps:
    - uses: actions/checkout@v2
    - uses: ayltai/setup-graalvm@v1
      with:
        java-version: 8
        graalvm-version: 20.3.1
        native-image: true
    - uses: ilammy/msvc-dev-cmd@v1.5.0
      if: runner.os == 'Windows'
    - uses: microsoft/setup-msbuild@v1
      if: runner.os == 'Windows'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn package
      run: |
        mkdir dist
        mvn -DskipTests -V package -P native
        ${{ matrix.move }} target${{ matrix.separator }}classes${{ matrix.separator }}rsc-e2e-${{ matrix.classifier }}${{ matrix.extension }} dist${{ matrix.separator }}${{ matrix.file }}
    - name: upload-dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist