name: coursier
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: laughedelic/coursier-setup@v1
      with:
        apps: rsc --contrib
    - name: test
      run: |
        rsc --version
        rsc --showSystemProperties
        rsc ws://rsocket-demo.herokuapp.com/rsocket --route searchTweets --stream -d Trump --take 3 --retry 3 --debug
        rsc wss://rsocket-demo.herokuapp.com/rsocket --route searchTweets --stream -d Trump --take 3 --retry 3 --debug
